language: ruby
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true
