language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "iojs"
cache:
  directories:
    - node_modules
install:
  - docker build -t sputnik .
  - docker run -d -p 127.0.0.1:80:80 --name sputnik
script:
- docker ps | grep -q sputnik
