language: node_js
node_js:
  - "5"
  - "5.1"
  - "iojs"

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

cache:
  directories:
    - node_modules

script:
  - docker-compose build
  - docker-compose up
  - npm test
