language: node_js
node_js:
  - "5"
  - "5.1"

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

cache:
  directories:
    - node_modules

script:
  - npm test # this can fail if database/tables do not exist!
  # - docker-compose build
