language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "iojs"
sudo: required
services:
  - docker
before_install:
  - dinghy up
  - docker-compose build
  - docker-compose up
cache:
  directories:
    - node_modules
# script:
#   - docker-compose build
#   - docker-compose run test
