language: node_js
node_js:
  - "5"
  - "5.1"
  - "iojs"

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

cache:
  directories:
    - node_modules

script:
  - docker-compose build
  # Test if server will start
  # Keep commented out for now
  # - docker-compose up
  - npm test # this can fail if database/tables do not exist!
